apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-code-pvc
  namespace: development
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 30Gi
  storageClassName: hostpath

---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-code
  namespace: development
  labels:
    app: k8s-code
spec:
  securityContext:
    seccompProfile:
      type: "RuntimeDefault"
    runAsNonRoot: true
  containers:
    - image: k8s-code:latest
      imagePullPolicy: IfNotPresent
      name: k8s-code
      resources:
        limits:
          cpu: "4000m"
          memory: "8Gi"
        requests:
          cpu: "2000m"
          memory: "2Gi"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      volumeMounts:
        - mountPath: /home/vscode
          name: k8s-code
          readOnly: false
  volumes:
    - name: k8s-code
      persistentVolumeClaim:
        claimName: k8s-code-pvc
